version: "3"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  go:
    image: golang
    working_dir: /app
    command: go run /app/cmd/wallcast/main.go
    volumes:
      - .:/app